name: Lint
  on:
    pull_request:
      branches:
        - main
    push:
      branches:
        - main
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install test dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[test]
      - name: Run ruff
        run:
          ruff check --output-format=github .